png("plot3.png", width=480, height=480) 
plot(datetime, data1$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="") 
lines(datetime,data1$Sub_metering_2,col = "red")
lines(datetime, data1$Sub_metering_3, type="l", col="blue") 
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue")) 
dev.off()